apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      app: webapp-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-deployment
    spec:
      containers:
      - name: api
        image: yunusemrecatalcam/ci-cd-webapp:latest
        ports:
          - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: webapp-deployment
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: webapp2.scrapesoup.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp-service
          servicePort: 8000